config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails, :preview_email
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'contacts#show', :as => "tabs"
      get 'load_tab' => 'contacts#load_tab', :as => "load_tab"
    end
    resources :contacts_projects, :path => "projects", :only => [:new, :create, :destroy]
  end

  resources :projects do
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do
        get :contacts_notes
      end
    end

  end

  resources :projects do
    resources :crm_queries, :only => [:new, :create]
  end

  resources :crm_queries, :except => [:show]

  resources :notes

  match '/contacts_tags', :controller => 'contacts_tags', :action => 'destroy', :via => :delete

  resources :contacts_tags do
    collection do
      post :merge, :context_menucha
      get :context_menu, :merge
    end
  end

  match 'projects/:project_id/contacts/:contact_id/new_task' => 'contacts_issues#new', :via => :post

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index', :via => [:get, :post]

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new', :via => [:get, :post]


  match 'auto_completes/taggable_tags' => 'auto_completes#taggable_tags', :via => :get, :as => 'auto_complete_taggable_tags'
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'

  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates', :via => [:get, :post]
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_issues/:action' => 'contacts_issues', :via => [:get, :post, :delete, :put]
  match 'contacts_vcf/:action' => 'contacts_vcf', :via => [:get, :post]
  match 'deal_contacts/:action' => 'deal_contacts', :via => [:get, :post, :delete]
  match 'deals_tasks/:action' => 'deals_tasks', :via => [:get, :post, :put]
  match 'contacts_settings/:action' => 'contacts_settings', :via => [:get, :post]
  match 'contacts_mailer/:action' => 'contacts_mailer', :via => [:get, :post]
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

app/helpers/contacts_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

module ContactsHelper

  def contact_tabs(contact)
    contact_tabs = []
    contact_tabs << {:name => 'notes', :partial => 'contacts/notes', :label => l(:label_crm_note_plural)} if contact.visible?
    contact_tabs << {:name => 'contacts', :partial => 'company_contacts', :label => l(:label_contact_plural) + (contact.company_contacts.visible.count > 0 ? " (#{contact.company_contacts.count})" : "")} if contact.is_company?
    contact_tabs
  end

  def settings_contacts_tabs
    ret = [
      {:name => 'general', :partial => 'settings/contacts/contacts_general', :label => :label_general},
      {:name => 'money', :partial => 'settings/contacts/money', :label => :label_crm_money_settings},
    ]
    ret.push({:name => 'hidden', :partial => 'settings/contacts/contacts_hidden', :label => :label_crm_contacts_hidden}) if params[:hidden]
    ret
  end

  def collection_for_visibility_select
    [[l(:label_crm_contacts_visibility_project), Contact::VISIBILITY_PROJECT],
     [l(:label_crm_contacts_visibility_public), Contact::VISIBILITY_PUBLIC],
     [l(:label_crm_contacts_visibility_private), Contact::VISIBILITY_PRIVATE]]
  end

  def contact_list_styles_for_select
    list_styles = [[l(:label_crm_list_excerpt), "list_excerpt"]]
  end

  def contacts_list_style
    list_styles = contact_list_styles_for_select.map(&:last)
    if params[:contacts_list_style].blank?
      list_style = list_styles.include?(session[:contacts_list_style]) ? session[:contacts_list_style] : RedmineContacts.default_list_style
    else
      list_style = list_styles.include?(params[:contacts_list_style]) ? params[:contacts_list_style] : RedmineContacts.default_list_style
    end
    session[:contacts_list_style] = list_style
  end

  def authorized_for_permission?(permission, project, global = false)
    User.current.allowed_to?(permission, project, :global => global)
  end

  def render_contact_projects_hierarchy(projects)
    s = ''
    project_tree(projects) do |project, level|
      s << "<ul>"
      name_prefix = (level > 0 ? ('&nbsp;' * 2 * level + '&#187; ') : '')
      s << "<li id='project_#{project.id}'>" + name_prefix + link_to_project(project)

      s += ' ' + link_to(image_tag('delete.png'),
                                 contact_contacts_project_path(@contact, :id => project.id, :project_id => @project.id),
                                 :remote => true,
                                 :method => :delete,
                                 :style => "vertical-align: middle",
                                 :class => "delete",
                                 :title => l(:button_delete)) if (projects.size > 1 && User.current.allowed_to?(:edit_contacts, project))
      s << "</li>"

      s << "</ul>"
    end
    s.html_safe
  end

  def contact_to_vcard(contact)
    return false unless ContactsSetting.vcard?

    card = Vcard::Vcard::Maker.make2 do |maker|

      maker.add_name do |name|
        name.prefix = ''
        name.given = contact.first_name.to_s
        name.family = contact.last_name.to_s
        name.additional = contact.middle_name.to_s
      end

      maker.add_addr do |addr|
        addr.preferred = true
        addr.street = contact.street1.to_s.gsub("\r\n"," ").gsub("\n"," ")
        addr.locality = contact.city.to_s
        addr.region = contact.region.to_s
        addr.postalcode = contact.postcode.to_s
        addr.country = contact.country.to_s
        addr.location = 'business'
      end

      maker.title = contact.job_title.to_s
      maker.org = contact.company.to_s
      maker.birthday = contact.birthday.to_date unless contact.birthday.blank?
      maker.add_note(contact.background.to_s.gsub("\r\n"," ").gsub("\n", ' '))

      maker.add_url(contact.website.to_s)

      contact.phones.each { |phone| maker.add_tel(phone) }
      contact.emails.each { |email| maker.add_email(email) }
    end
    avatar = contact.attachments.find_by_description('avatar')
    card = card.encode.sub("END:VCARD", "PHOTO;BASE64:" + "\n " + [File.open(avatar.diskfile).read].pack('m').to_s.gsub(/[ \n]/, '').scan(/.{1,76}/).join("\n ") + "\nEND:VCARD") if avatar && avatar.readable?

    card.to_s

  end

  def set_flash_from_bulk_contact_save(contacts, unsaved_contact_ids)
    if unsaved_contact_ids.empty?
      flash[:notice] = l(:notice_successful_update) unless contacts.empty?
    else
      flash[:error] = l(:notice_failed_to_save_contacts,
                        :count => unsaved_contact_ids.size,
                        :total => contacts.size,
                        :ids => '#' + unsaved_contact_ids.join(', #'))
    end
  end

  def render_contact_tabs(tabs)
    if tabs.any?
      render :partial => 'common/contact_tabs', :locals => {:tabs => tabs}
    else
      content_tag 'p', l(:label_no_data), :class => "nodata"
    end
  end


end

app/views/settings/contacts/_contacts.html.erb
<% extend ContactsHelper %>

<%= render_tabs settings_contacts_tabs %>

<% html_title(l(:label_settings), l(:label_contact_plural)) -%>

app/views/settings/contacts/_contacts_general.html.erb
<p>
  <label><%= l(:label_crm_user_format) %></label>
  <%= select_tag 'settings[name_format]', options_for_select(Contact::CONTACT_FORMATS.collect{|key, value| [key, value[:setting_order]]}.sort{|a, b| a[1] <=> b[1]}.collect{|f| [Contact.new(:first_name => 'Firstname', :last_name => 'Lastname', :middle_name => 'Middlename').name(f[0]), f[0].to_s]}, @settings[:name_format] ) %>
</p>

<p>
  <label><%= l(:label_crm_post_address_format) %></label>
  <%= text_area_tag  'settings[post_address_format]', ContactsSetting.post_address_format, :rows => 5 %>
  <em class="info"><%= l(:label_crm_post_address_format_macros, :macros => '%street1%, %street2%, %city%, %town%, %postcode%, %zip%, %region%, %state%, %country%') %></em>
</p>

<p>
  <label><%= l(:label_crm_default_country) %></label>
  <%= select_tag  'settings[default_country]', options_for_select(countries_for_select, ContactsSetting.default_country) %>
</p>

<p>
  <label><%= l(:label_crm_show_in_top_menu) %></label>
  <span id="watchers_inputs">
    <span class="floating" style="margin-left: 0px;">
    <%= check_box_tag 'settings[contacts_show_in_top_menu]', 1, @settings[:contacts_show_in_top_menu] %>
    <%= l(:label_contact_plural) %>
    </span>
  </span>
</p>

<p>
  <label><%= l(:label_crm_show_in_app_menu) %></label>
  <span id="watchers_inputs">
    <span class="floating" style="margin-left: 0px;">
    <%= check_box_tag 'settings[contacts_show_in_app_menu]', 1, @settings[:contacts_show_in_app_menu] %>
    <%= l(:label_contact_plural) %>
    </span>
  </span>
</p>


<p>
  <label><%= l(:label_crm_contact_note_authoring_time) %></label>
  <%= check_box_tag 'settings[note_authoring_time]', 1, @settings[:note_authoring_time] %>
</p>

<p>
  <label><%= l(:label_crm_contact_show_in_app_menu) %></label>
  <%= check_box_tag 'settings[show_in_app_menu]', 1, @settings[:show_in_app_menu] %>
</p>

<p>
  <label><%= l(:label_crm_contact_show_closed_issues) %></label>
  <%= check_box_tag 'settings[show_closed_issues]', 1, @settings[:show_closed_issues] %>
</p>

<p>
  <label><%= l(:label_crm_monochrome_tags) %></label>
  <%= check_box_tag 'settings[monochrome_tags]', 1, @settings[:monochrome_tags] %>
</p>

app/views/settings/contacts/_contacts_hidden.html.erb
<p>
  <label>Monochrome tags</label>
  <%= check_box_tag 'settings[monochrome_tags]', 1, @settings[:monochrome_tags] %>
</p>

app/views/settings/contacts/_contacts_tags.html.erb
<% tags = Contact.all_tag_counts(:order => :name) %>

<h3><%= l(:label_crm_tags_plural) %></h3>

<% unless tags.empty? %>
<table class  = "list issues">
  <thead>
    <tr>
      <th class="checkbox hide-when-print">
        <%= link_to image_tag('toggle_check.png'), {},
                              :onclick => 'toggleIssuesSelection(this); return false;',
                              :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
      </th>
      <th><%= l(:field_name) %></th>
      <th align="center" style="width:10%;"> </th>
    </tr>
  </thead>
  <tbody>
    <% tags.each do |tag| %>
      <tr id="<%= tag.id %>" class="<%= cycle("odd", "even") %> hascontextmenu ">
        <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", tag.id, false, :id => nil) %></td>
        <td class="name"><%= tag_link(tag.name) %></td>
        <td class="buttons">
          <%= link_to l(:button_edit), edit_contacts_tag_path(tag),
                                         :class => 'icon icon-edit' %>

          <%= link_to l(:button_delete), contacts_tags_path(:ids => tag),
                                         :method => :delete,
                                         :confirm => l(:text_are_you_sure),
                                         :class => 'icon icon-del' %>
          </td>

      </tr>

    <% end %>
  </tbody>
</table>
<%= context_menu context_menu_contacts_tags_path %>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/settings/contacts/_money.html.erb
<p>
  <label><%= l(:label_crm_disable_taxes) %></label>
  <%= check_box_tag 'settings[disable_taxes]', 1, ContactsSetting.disable_taxes? %>
</p>

<span id="tax_data">
<p>
  <label><%= l(:label_crm_default_tax) %></label>
  <%= text_field_tag 'settings[default_tax]', ContactsSetting.default_tax, :size => 6, :maxlength => 5 %> %
</p>

<p>
  <label><%= l(:label_crm_tax_type) %></label>
  <%= select_tag 'settings[tax_type]', options_for_select([[l(:label_crm_tax_type_exclusive), ContactsSetting::TAX_TYPE_EXCLUSIVE],
                                                                  [l(:label_crm_tax_type_inclusive), ContactsSetting::TAX_TYPE_INCLUSIVE]], ContactsSetting.tax_type) %>
</p>
</span>

<p>
  <label><%= l(:label_crm_default_currency) %></label>
  <%= select_tag 'settings[default_currency]', options_for_select(all_currencies.insert(0, ['', '']), ContactsSetting.default_currency) %>
</p>

<p>
  <label><%= l(:label_crm_major_currencies) %></label>
  <%= text_field_tag 'settings[major_currencies]', ContactsSetting.major_currencies.join(', '), :size => 40 %>
  <br>
  <em class="info"><%= l(:text_comma_separated) %></em>
</p>

<p>
  <label><%= l(:label_crm_thousands_delimiter) %></label>
  <%= select_tag 'settings[thousands_delimiter]',  options_for_select([["9 999", " "],
                                                                       ["9,999", ","],
                                                                       ["9.999", "."]], ContactsSetting.thousands_delimiter) %>
</p>

<p>
  <label><%= l(:label_crm_decimal_separator) %></label>
  <%= select_tag 'settings[decimal_separator]',  options_for_select([["0.00", "."],
                                                                     ["0,00", ","]], ContactsSetting.decimal_separator) %>
</p>